### ISSUE TITLE
build from source

### ISSUE THREAD

**Issue by kbrock** [matsumotory/ngx_mruby#106]
Is there a way to build from the source without using git?

I downloaded the source `https://github.com/matsumoto-r/ngx_mruby/archive/v1.7.8.tar.gz` from the releases page.

It does download nginx, but fails when trying to build mruby. (obviously the submodules were not downloaded)

Any ideas how to download that or build it?

Thanks

**Comment by matsumoto-r** [comment]
@kbrock ngx_mruby just now supports subtree. https://github.com/matsumoto-r/ngx_mruby/pull/139

The source archive include dependent packages like mruby. Sorry for my late response. Thanks!
