### ISSUE TITLE
Building ngx in more standard way

### ISSUE THREAD

**Issue by kbrock** [matsumotory/ngx_mruby#135]
Hello,

I like how well ngx_mruby did in the [benchmark](https://www.techempower.com/benchmarks/#section=data-r10&hw=peak&test=db) comparisons with other servers. I also feel being the fastest ruby (by far) is very cool, too.

Unfortunately the procedure for building `ngx_mruby` is a little intimidating for me. ( [setup](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Ruby/ngx_mruby/setup.sh) )
I need to add [merb](https://github.com/pbosetti/mruby-merb) for templating and possibly a database connection pool, but feel the current way I built it is a little hacky.

Do you have comments for the following improvements?
1. I can build mruby with rvm/ruby-install/ruby-build. Can I just link that while building `ngx_mruby` using something like `-I/home/mruby/lib/mruby.a -lmruby`? Do we really need to download mruby inside of `ngx_mruby` source?
2. Do I need to rebuild `mruby` for every gem, or can I just add the gem in a similar way mentioned above `-lmruby-merb`?
3. ~~Can I build ngx using their module syntax like `cd ngx ; ./configure --add-module=$HOME/ngx_mruby`~~ See [install](https://github.com/matsumoto-r/ngx_mruby/wiki/Install#or-configure-with---add-modulengx_mruby_src-for-nginx-and-make-it) notes

I'm very happy to do the work, just hope you would have pointers to what is possible, and what path you would like me to take.

Thank you,
Keenan

**Comment by matsumoto-r** [comment]
Thank you for your suggest. Please let me consider about this issue.

**Comment by kbrock** [comment]
I think the issue is probably my lack of understanding.

Do you have a suggestion on how I can change the install of mysql? [benchmarks](
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Ruby/ngx_mruby/setup.sh#L26)

**Comment by matsumoto-r** [comment]
@kbrock 

Thank you for the question. When you want to add other mrbgem to ngx_mruby, you can add the following code into [ngx_mruby/build_config.rb](https://github.com/matsumoto-r/ngx_mruby/blob/master/build_config.rb#L10-L29);

```ruby
conf.gem :github => "mattn/mruby-mysql"
conf.gem :github => "pbosetti/mruby-merb"
```

**Comment by scalp42** [comment]
@kbrock did you figure the answer to these questions by any chance ? Would come in handy as I'm having the same questions :smile: 


cc @matsumoto-r

**Comment by yyamano** [comment]
We need to change mruby/mrbgem build system to support such features. And rvm/ruby-install/ruby-build too. They are for binary installation like mruby command, not for embedding mruby into applications. It's a lot of work.

@kbrock @scalp42  Could you explain specific problems with current ngx_mruby build process?
Downloading mruby source many times? Rebuilding mruby every time you add a new gem? Or something else?

**Comment by yyamano** [comment]
No feedback for over three months. Please feel free to reopen it if necessary.
