### ISSUE TITLE
How use password to redis?

### ISSUE THREAD

**Issue by yukui** [matsumotory/ngx_mruby#230]

**Comment by yyamano** [comment]
@yukui Could you see https://github.com/matsumotory/mruby-redis#connecting-to-a-redis-server ? redis auth is implemented 5 days ago.

**Comment by yyamano** [comment]
@matsumotory Could you close it? No feedback for a while.

**Comment by matsumotory** [comment]
Yes! I will leave it to your judgment like this issue.

**Comment by matsumotory** [comment]
@yyamano We add you to collaborators. Please check e-mail and close this issue!

**Comment by yyamano** [comment]
@matsumotory thx!
