### ISSUE TITLE
Proposal to remove mruby_test

### ISSUE THREAD

**Issue by yyamano** [matsumotory/ngx_mruby#242]
I'd like to remove mruby_test to avoid having 2 copies of mruby in the repo.
Here is my change.  https://github.com/yyamano/ngx_mruby/commit/7467c766930d191a08ad84da23d86479a248c81b

Pros:

* No more 2 copies ot mruby source
* Tracking mruby is easy.

Cons: 

* mruby/build/test is always built even if you don't run test.
* Syncing build_config.rb and build_config_dynamic.rb with mruby/build_config.rb is cumbersome.

Any thoughts?

**Comment by matsumotory** [comment]
Thank you for your proposal. Previously I built it with a single mruby, but it is hard to debug and cost to build every time is high so I made it to build multiple mruby. So, I like to use multiple at present.

**Comment by yyamano** [comment]
Would you tell me details about debugging problems you had with single mruby source?
I understand that building mruby/build/host and mruby/build/test at the same time is not acceptable.

I'd like to simplify ngx_mruby build system.

**Comment by matsumotory** [comment]
Oh, sorry. I was misunderstanding. There is no problem if you put the mruby binaries into different directories by one build_config. After that, it is even better to be able to distinguish build targets with rake.

**Comment by matsumotory** [comment]
So, I'd like to accept your proposal. Could you send the PR? I'll review it.

**Comment by yyamano** [comment]
I rebased and sent a pull request. #243
