### ISSUE TITLE
Recent docker images on Docker Hub are not built

### ISSUE THREAD

**Issue by minimum2scp** [matsumotory/ngx_mruby#294]
Latest tag is built at 7 months ago.
https://hub.docker.com/r/matsumotory/ngx-mruby/

![image](https://cloud.githubusercontent.com/assets/162862/26534406/cd3aaed6-445e-11e7-88a3-7aec8a928a57.png)

```console
% docker pull matsumotory/ngx-mruby
Using default tag: latest
latest: Pulling from matsumotory/ngx-mruby
Digest: sha256:c96a0f8ff3ab7af1132828b11a4e07ccf525f7626f6229fd5f4dbde06b4f34ac
Status: Image is up to date for matsumotory/ngx-mruby:latest
% docker run --rm -w /usr/local/src/ngx_mruby matsumotory/ngx-mruby git show
commit 0995a5cc133a6deec28cc5870fd3bfb152e1cf4c
Merge: 637ec3c 3deefb1
Author: MATSUMOTO, Ryosuke <matsumoto_r@net.ist.i.kyoto-u.ac.jp>
Date:   Sat Oct 29 15:47:54 2016 +0900

    Merge pull request #228 from kenhys/fix-certficate
    
    Fix a typo

```

GitHub repository name was changed at 2016-12-17 (#247), but
perhaps Docker Hub (automated build) settings were not changed.

**Comment by yyamano** [comment]
Looks it was already fixed. https://hub.docker.com/r/matsumotory/ngx_mruby/builds/

@webuilder240  If you are still have the problem, feel free to re-open this.
