### ISSUE TITLE
Stack deep when run funcall instead of mrb_rux

### ISSUE THREAD

**Issue by matsumotory** [matsumotory/ngx_mruby#364]
#363 

We should investigate the root cause.

**Comment by matsumotory** [comment]
これどのコミットで解決したかわからないので、次回からはそれらが追えるようにコミットログをもう少し後から見てもわかる文章でちゃんと書くようにしときましょうか。

**Comment by matsumotory** [comment]
イメージとしては僕が書いているようなコミットの感じで、

https://github.com/matsumotory/ngx_mruby/pull/343/commits

どういう問題や処理が解決されたのかみたいな観点で、動詞からはじめる(僕は最初大文字)ように書いておくと、後でバグの見直しの振り返りでも追いやすくなるように思います。

**Comment by pyama86** [comment]
これ、解消してないというか起きなくなってます。

https://github.com/matsumotory/ngx_mruby/pull/363

**Comment by pyama86** [comment]
事象が起きてた原因は

https://github.com/matsumotory/ngx_mruby/pull/363/files#diff-bbdc89dae16aa5c53566f7ec784a35b3L40

この部分でmrb->excをみてないからexceptionが無視されておかしくなるみたいな挙動をしてたはず。

**Comment by matsumotory** [comment]
excを見るようにしたコミットはどれかわかります？

**Comment by pyama86** [comment]
それが上のPRでそもそもmrb_funcallやめてます！

**Comment by matsumotory** [comment]
excをみるかみないかと、mrb_runかmrb_funcallを使うかどうかは関係ないように思えますが、mrb_funcall使った場合だとどういう書き方になるか、根本原因はどう解決されるのかを知りたいという意図のissueですね。#363 はmrb_runにしたらひとまず治るよね、というprだったと記憶しています。

**Comment by matsumotory** [comment]
で、ここの原因わかった！って口頭で細かく話してた記憶がある…

**Comment by pyama86** [comment]
はい！その原因はmrb_funcallの例外処理してないことだったのですが、そもそも実装が既にないということです！

**Comment by matsumotory** [comment]
上記の実装でも、funcall後にwithout_stop関数でたあとで例外処理をちゃんと見ているように読めるので、それだと説明つかない気がしますがそういう意味ではないです？

ちとここはまた具体的に明らかになったら追記してcloseするとして、こういうソフトウェアのコミットは、コミット自体の価値も高まってくるのと、数行のコミットと数日の調査で難解な問題を解決みたいなのが多々あるので、面倒だとは思いますができるだけコミットログをしっかり書く感じでやっていきましょう。1行しっかり書くという意味ではそれほどコストも高くはないと思いますので。あれだったは日本語でも良いです！

**Comment by matsumotory** [comment]
https://github.com/matsumotory/ngx_mruby/pull/363#pullrequestreview-125382292

ここにコメントが付いてたの転載。ありがとうございます。つまり、funcallを使った場合も先に例外処理をやっておけば良さそう。いずれmrb_run使っている方も非同期対応していく中でfuncallはいるので、その時にはその実装を忘れずやる。
