### ISSUE TITLE
BUG?: using Nginx::Utils.encode_parameters like the following script  is sometimes missing call method for fiber_proc

### ISSUE THREAD

**Issue by matsumotory** [matsumotory/ngx_mruby#377]
ref: 1b3a54da3bbdd7c9aeb5ff97bf94045a3ee345a4

**Comment by matsumotory** [comment]
more information: https://github.com/matsumotory/ngx_mruby/pull/376#issuecomment-395978703

**Comment by yyamano** [comment]
@matsumotory can you reproduce this with the latest version of ngx_mruby? 
https://github.com/matsumotory/ngx_mruby/commit/8b73427caf46215d9909a02e338749d250ec1e7f works fine to me.

**Comment by pyama86** [comment]
:eyes

**Comment by matsumotory** [comment]
Oh, lgtm. Thanks!
