### ISSUE TITLE
Missing updating documentation for mruby and dependence/ngx_devel_kit

### ISSUE THREAD

**Issue by yyamano** [matsumotory/ngx_mruby#381]
The title says all. 

We have update-mruby-subtree script for mruby, but it's not documented.

**Comment by matsumotory** [comment]
Yes, please create docs/DEVELOPMENT.md.

**Comment by yyamano** [comment]
We have docs/DEVELOPMENT.md now. Anyone can write ngx_devel_kit updating procedure?

**Comment by matsumotory** [comment]
Update via #402 . Thanks!
