### ISSUE TITLE
checking for GD library in /opt/local/ ... not found ( Application failed )

### ISSUE THREAD

**Issue by gaukhush** [matsumotory/ngx_mruby#416]
Hi Matsumotory 

When using ngx_mruby to build application it fails as below. 

-------------------------------------------------------------------
checking for GD library in /usr/local/ ... not found
checking for GD library in /usr/pkg/ ... not found
checking for GD library in /opt/local/ ... not found

./configure: error: the HTTP image filter module requires the GD library.
You can either do not enable the module or install the libraries.

--------------------------------------------

It looks like something went wrong

Please read our documentation for troubleshooting tips:

   https://www.phusionpassenger.com/library/install/nginx/
   https://www.phusionpassenger.com/library/admin/nginx/troubleshooting/

If that doesn't help, please use our support facilities. We'll do our best to help you.

   https://www.phusionpassenger.com/support

**Comment by yyamano** [comment]
@gaukhush I just want to make sure you are trying to build nginx with ngx_mruby and passenger modules?
Could you tell us what operations you have done?

**Comment by gaukhush** [comment]
@yyamano thanks for quick reply, last fork 1 month worked to build nignx via ngx_mruby with passenger but when tried yesterday multiple times via ngx_mruby it fails. We call ngx_mruby from repo saturn which is mentioned below and uses passenger version 5.3.3. 

`#!/bin/bash -e

if [ `whoami` != 'root' ]; then
  echo "This script should be run as root"
  exit
fi

SOURCE="${BASH_SOURCE[0]}"
SOURCE_DIR="$( dirname "$SOURCE" )"

echo "=== Cloning ngx_mruby ==="
git clone https://github.com/gaukhush/ngx_mruby.git

echo "=== Switch to branch ==="
cd ngx_mruby
git checkout master

echo "=== Build mruby and others ==="
BUILD_DYNAMIC_MODULE=TRUE sh build.sh
cd ..

echo "=== Clone passenger ==="
git clone https://github.com/phusion/passenger
cd passenger
git checkout release-5.3.3
git submodule update --init --recursive
cd ..

$SOURCE_DIR/build_nginx.sh`


1. We just invoke build_all.sh which has ngx_mruby all modules to downloan nginx latest and build passenger application. 
2. This started failing at last step as 
`checking for GD library in /usr/local/ ... not found
checking for GD library in /usr/pkg/ ... not found
checking for GD library in /opt/local/ ... not found

./configure: error: the HTTP image filter module requires the GD library.
You can either do not enable the module or install the libraries`

**Comment by yyamano** [comment]
@gaukhush I can't reproduce it. 
I don't think it's a ngx_mruby issue. It's a nginx configuration or your build env issue.

> ./configure: error: the HTTP image filter module requires the GD library.
> You can either do not enable the module or install the libraries.

As the message suggests, you need to install the GD library if you want to use the module.

**Comment by gaukhush** [comment]
@yyamano agree with you and managed to install dependencies like(libgd, libgeoip, libatomic_ops) finally i below error. Earlier this was not coming, i think passenger repo has some changes done to include these dependencies. Can you check below error and give a thought ?

-Wl,-E -ldl -lpthread -lcrypt /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/LoggingKit.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Exceptions.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/FileTools/PathManip.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/FileTools/FileManip.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/FileTools/PathSecurityCheck.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/ProcessManagement/Spawn.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/ProcessManagement/Utils.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Utils/SystemTime.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Utils/StrIntUtils.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Utils/StrIntUtilsNoStrictAliasing.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Utils/IOUtils.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Utils/Hasher.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Utils.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/jsoncpp.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/WatchdogLauncher.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/AppTypes.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Utils/CachedFileStat.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/JsonTools/CBindings.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/FileTools/PathManipCBindings.o /usr/local/shopmatic/passenger/buildout/common/libboost_oxt.a -lstdc++ -lpthread -lm -lrt -L/usr/local/shopmatic/ngx_mruby/mruby/build/host/lib -L/usr/local/lib -lmruby -lm -lreadline -lcrypto -lpthread -lpthread -lrt -lpthread -lrt /usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/lib/libhiredis.a -L -lmruby -lstdc++ -lpcre -lssl -lcrypto -ldl -lpthread -lz -lxml2 -lxslt -lexslt -lgd -lGeoIP -latomic_ops \
-Wl,-E -fstack-protector-strong -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lc -lcrypt \
-Wl,-E
/usr/bin/ld: cannot find -lperl
collect2: error: ld returned 1 exit status
objs/Makefile:349: recipe for target 'objs/nginx' failed
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory '/usr/local/shopmatic/ngx_mruby/build_dynamic/nginx-1.15.7'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by yyamano** [comment]
> /usr/bin/ld: cannot find -lperl

@gaukhush I've never used passenger. I guess you need to install libperl.so or add -L/path/to/libperl/dir.

**Comment by gaukhush** [comment]
ok let me check on this.

**Comment by yyamano** [comment]
@gaukhush Did you resolve the issue?

**Comment by gaukhush** [comment]
@yyamano thanks for waiting and i got some time lastweek and i was able to resolved by installing multiple libraries as mentioned. 

cd /usr/local
sudo wget https://github.com/libgd/libgd/releases/download/gd-2.2.5/libgd-2.2.5.tar.gz
sudo tar -xvof libgd-2.2.5.tar.gz
sudo mv libgd-2.2.5.tar.gz /tmp
cd libgd-2.2.5
sudo ./configure
sudo make
sudo make install

sudo wget http://www.maxmind.com/app/c
sudo wget https://github.com/maxmind/geoip-api-c/releases/download/v1.6.11/GeoIP-1.6.11.tar.gz
sudo tar -xvof GeoIP-1.6.11.tar.gz
sudo mv GeoIP-1.6.11.tar.gz /tmp
cd GeoIP-1.6.11
sudo ./configure
sudo make
sudo make install

sudo wget https://github.com/ivmai/libatomic_ops/releases/download/v7.6.8/libatomic_ops-7.6.8.tar.gz
sudo tar -xvof libatomic_ops-7.6.8.tar.gz
sudo mv libatomic_ops-7.6.8.tar.gz /tmp
cd libatomic_ops-7.6.8
sudo ./configure
sudo make
sudo make install

sudo apt install libgd-dev
sudo apt install libwebp-dev
sudo apt install libgd-lua
sudo apt install libperl-dev
cd /usr/local/libgd-2.2.5
sudo ./configure --with-webp
sudo make
sudo make install
cd /usr/local/shopmatic
sudo rm -rf *
sudo ~/saturn/nginx/build_all.sh

**Comment by yyamano** [comment]
@gaukhush That's great to hear!
