### ISSUE TITLE
About upgrade mruby to 2.0.1

### ISSUE THREAD

**Issue by ynishi** [matsumotory/ngx_mruby#431]
I've upgraded mruby and made pr #430 .

The mainly reason is that the first version of mruby 2.0.0 on 11 Dec is not support `#to_int` method, and recover at 17 Dec by https://github.com/mruby/mruby/commit/e690314525d3ebfa23eda9f2cacfff37bd53482a

So the version merged at #415 can't use `#to_int` and fail to call `SecureRandom#uuid` because it always uses `#to_int`.
https://github.com/monochromegane/mruby-secure-random/blob/master/mrblib/mrb_securerandom.rb#L56

I think it is good way ​​to upgrade to the latest tag 2.0.1 as of September 2019.

**Comment by matsumotory** [comment]
I agree with you and merged that PR. Thanks!
