### ISSUE TITLE
Discussion about test with normal ruby

### ISSUE THREAD

**Issue by Zogoo** [matsumotory/ngx_mruby#435]
I just start to look at the source code. 
And I thought why test can't be written by normal Ruby with Ruby libraries. 
For example: 
 1. SSL request test cases can easily done with "net/http".

**Comment by Zogoo** [comment]
@matsumotory thanks for your reply.

Does it mean you guys are creating some new mruby gems for your tests?

Actually, Reason of asking this, if normal ruby test was allowed I would like work on following pull request's test.

https://github.com/matsumotory/ngx_mruby/pull/338

Because, I need to use this feature and seems like only test task left on this pull request.

So, I was thinking that I will try to create proper test with openssl ruby gem and net/http for client certificate validation.

**Comment by matsumotory** [comment]
The test of that Pull-Request can be solved by openssl command, I guess. So you can write the mruby code included openssl commands.

**Comment by yyamano** [comment]
I think the point is how much easier, not can or can  not.

I wrote cruby test code for my ngx_mruby projects. I run both my own cruby test and mruby test from ngx_mruby on travis.

**Comment by Zogoo** [comment]
> I think the point is how much easier, not can or can not.
> 
> I wrote cruby test code for my ngx_mruby projects. I run both my own cruby test and mruby test from ngx_mruby on travis.

I didn't know you already did it. I will take a look your project then.

**Comment by matsumotory** [comment]
Ok, even if we can implement test easily by CRuby, I think we should implement the test by mruby because of contributions for mruby.

**Comment by yyamano** [comment]
> I didn't know you already did it. I will take a look your project then.

I'm sorry I didn't make it clear enough. They are private projects. I can't make them public.

**Comment by yyamano** [comment]
@matsumotory Fair enough.

**Comment by Zogoo** [comment]
@matsumotory I got your idea. Thanks for your reply.

**Comment by Zogoo** [comment]
> > I didn't know you already did it. I will take a look your project then.
> 
> I'm sorry I didn't make it clear enough. They are private projects. I can't make them public.

@yyamano I was just checking your public github repo. If you guys decide to make your project public and if you drop some message in here that will be a great help for me.

**Comment by matsumotory** [comment]
@yyamano Thank you always for your understanding!

@Zogoo So, can I close this issue? Or do you have any other questions or comments?

**Comment by Zogoo** [comment]
I don't have any questions. Let me close this issue.

**Comment by matsumotory** [comment]
OK! Thank you for your suggestions!
