### ISSUE TITLE
Failure to receive divided http requests.

### ISSUE THREAD

**Issue by kunichi3** [matsumotory/ngx_mruby#440]
I am processing data with the following simple code.

> location /api/test {
> 	mruby_enable_read_request_body on;
>     mruby_content_handler '/home/user/ruby/api.rb';
> }

In iOS, HTTP requests are sent divided into header and body.
Therefore, receiving HTTP requests from iOS frequently fails.
Is there any solution for this problem?

**Comment by matsumotory** [comment]
Thank you for your report. Cloud you paste your api .rb code here?

**Comment by kunio-fujiwara** [comment]
Thank you for your response.

api.rb code is simple.
> Nginx.rputs "test\n"

If the header and body are separated, this response will not return and will be deadlocked.

**Comment by kunichi3** [comment]
Thank you for your response.
api.rb code is simple.
>Nginx.rputs "test\n"

If the header and body are separated, this response will not return and will be deadlocked.

**Comment by matsumotory** [comment]
mruby_enable_read_request_body is a configuration to store all request bodies synchronously in mruby variables.  So basically you shouldn't use it if you don't read the request body. We should have implemented error handling and raised errors like that.

**Comment by kunichi3** [comment]
The above example shows the problem with the simplest configuration.
Of course, our implementation deals with body data.
The following code gives the same result.
```ruby
def getRequestBody(r)
    if !r.var.request_body.nil? then
        s = r.var.request_body
    elsif !r.var.request_body_file.nil? then
        h = {}
        f = open(r.var.request_body_file)
        s = f.readline
        f.close
    else
        return nil
    end
    return s
end

r = Nginx::Request.new
s = getRequestBody(r)
Nginx.rputs "#{s}\n"
```

**Comment by matsumotory** [comment]
Thank you for your details. So does it work if you read the request body on access_handler then pass the content to content_handler and create a response?

**Comment by kunichi3** [comment]
We didn't know how to combine access_handler and content_handler. We will check with a combination of access_handler and content_handler.
We'll inform you the result later. Thank you for your advice.

**Comment by matsumotory** [comment]
ref: https://github.com/matsumotory/ngx_mruby/tree/master/docs/class_and_method#nginxrequestget_body---string

**Comment by kunichi3** [comment]
The problem has been solved.
Thank you for your polite response.
m(_ _)m

**Comment by matsumotory** [comment]
You are welcome!
