### ISSUE TITLE
 Symbol not found: _mrb_sym2str

### ISSUE THREAD

**Issue by Zogoo** [matsumotory/ngx_mruby#448]
After I update my mruby and nginx with the latest master (v2.2.0) start to get following failure?

```
nginx: [emerg] dlopen() "/usr/local/nginx/modules/ngx_http_mruby_module.so" failed (dlopen(/usr/local/nginx/modules/ngx_http_mruby_module.so, 10): Symbol not found: _mrb_sym2str
  Referenced from: /usr/local/nginx/modules/ngx_http_mruby_module.so
  Expected in: flat namespace
 in /usr/local/nginx/modules/ngx_http_mruby_module.so) in /usr/local/nginx/conf/nginx.conf:12
```
Anything changed for build process?

**Comment by matsumotory** [comment]
Thank you for your report. I think this issue is a mruby specification. Please issue to mruby repository.

**Comment by Zogoo** [comment]
> Thank you for your report. I think this issue is a MRuby specification. Please issue to MRuby repository.

I have created issue for a MRuby repo with following url
https://github.com/mruby/mruby/issues/4934
, But I'm still not sure why Travis test environment looks like works fine not my local. Maybe some OSX or Clang issue?

**Comment by Zogoo** [comment]
@matsumotory I could solve this issue. When I delete mruby build folder (old version) the it's building correctly.  
That's mean `.minirake clean` not working for version update. What do you think if I add some shell in `build.sh` to delete mruby build folder if version different than current one.

**Comment by matsumotory** [comment]
That's sound good. Could you send the PR?

**Comment by Zogoo** [comment]
Seems like with new version might need specify build_config as like follow
`rake clean MRUBY_CONFIG=NGX_MRUBY_ROOT/build_config.rb` 
based on [answer of mruby issue](https://github.com/mruby/mruby/issues/4934#issuecomment-576566706)

**Comment by yyamano** [comment]
> What do you think if I add some shell in build.sh to delete mruby build folder if version different than current one.

@Zogoo I believe https://github.com/matsumotory/ngx_mruby/pull/453/commits/db45048d8ef4b527e60c56858a8589be4af59b0a fixes the issue.
