### ISSUE TITLE
Pass nil to Nginx::Headers_in[]= causes segmentaion fault

### ISSUE THREAD

**Issue by yano3** [matsumotory/ngx_mruby#473]
Pass `nil` to `Nginx::Headers_in[]=` causes segmentaion fault.

## Reproduce

```
server {
    listen       80;

    location / {
        mruby_content_handler_code '
          h = Nginx::Headers_in.new
          Nginx.echo h["X-FOO"]
          h["X-FOO"] = nil
        ';
    }
}
```

```
$ curl -H "X-FOO: foo" http://localhost:10080/
curl: (52) Empty reply from server
```

The following error is output to `error.log`.

```
2020/08/17 07:34:24 [alert] 1#1: worker process 27 exited on signal 11
```

This also happen with `Nginx::Headers_out[]=` too.

**Comment by yyamano** [comment]
@yano3 Thank you for the report. What is the expected behavior? Is throwing an exception fine?

**Comment by yano3** [comment]
In my use case, there is no problem with the behavior of throwing an exception. I only expect to avoid segmentation fault.

IMO, following behavior is good.

- If specified header exists, delete it.
- If specified header does not exist, do nothing.

For example, it's natural in the following case.

```
h = Nginx::Headers_in.new

# get header that does not exist
foo = h["X-FOO"] # => nil
h["X-FOO"] = foo
```

**Comment by yyamano** [comment]
Sounds good. I just sent a pull request #475

**Comment by yano3** [comment]
Thank you!

**Comment by matsumotory** [comment]
@yano3 @yyamano Thank you for your proposal!
