### ISSUE TITLE
Do you have plans to release the next version?

### ISSUE THREAD

**Issue by yano3** [matsumotory/ngx_mruby#499]
Since ngx_mruby v2.2.4 cannot be built with nginx 1.23.0 or higher, we need a new version number that includes the fixes in https://github.com/matsumotory/ngx_mruby/pull/496, I think.

**Comment by matsumotory** [comment]
I would like to use macros to branch the build according to the nginx version.

**Comment by matsumotory** [comment]
Oh, I took the meaning wrong. We will release the next version soon.

**Comment by matsumotory** [comment]
Released now. Thanks to @yano3 ! https://github.com/matsumotory/ngx_mruby/releases/tag/v2.2.5

**Comment by yano3** [comment]
Thank you!!
