### ISSUE TITLE
Can't build with mruby-localmemcache

### ISSUE THREAD

**Issue by dyarikov-sunbay** [matsumotory/ngx_mruby#507]
2.2.5 and 2.3.0 tags can't be built because of error:

/usr/src/nginx-1.23.1/ngx_mruby/mruby/build/repos/host/mruby-localmemcache/src/mruby_cache_gem.c:10:10: fatal error: mruby/internal.h: No such file or directory   10 | #include "mruby/internal.h"                                                   |          ^~~~~~~~~~~~~~~~~~                                             compilation terminated.                                                         
rake aborted!

**Comment by dyarikov-sunbay** [comment]
Looks like it can be avoided by running **touch mruby/include/mruby/internal.h** before building

**Comment by yyamano** [comment]
It is a known mruby-localmemcache's problem, not ngx_mruby's one. 
See https://github.com/matsumotory/mruby-localmemcache/issues/8 (written in Japanese)

**Comment by matsumotory** [comment]
Thanks all! Merged now https://github.com/matsumotory/mruby-localmemcache/issues/8
