### ISSUE TITLE
HTTP2 streming error when using mruby_output_header_filter

### ISSUE THREAD

**Issue by ry023** [matsumotory/ngx_mruby#508]
Hello!

The error will occur when using `mruby_output_header_filter` directive with HTTP2 multiplexing.
It looks that the nginx returns `INTERNAL_ERROR` by RST_STREAM http2 frame.
It doesn't occur when single request (not multiplexing).
It also doesn't occur when using http1.1 request. 

It is easy to reproduce on websites that display many images.
I'm debugging with reproduction environment here:

https://github.com/ry023/ngx_mruby_http2_debug

---

In chrome, the following error is output to the console;

<img width="672" alt="スクリーンショット 2023-08-02 14 14 53" src="https://github.com/matsumotory/ngx_mruby/assets/11782371/9403102c-b61d-4984-b53e-6e73d191203e">

I also debug with [my golang http2 client implement](https://github.com/ry023/ngx_mruby_http2_debug/tree/main/go-http-cli) and got `INTERNAL_ERROR`;

```
$ go run main.go
7.webp downloadded successfully
25.webp downloadded successfully
10.webp downloadded successfully
4.webp downloadded successfully
29.webp downloadded successfully
6.webp downloadded successfully
27.webp downloadded successfully
9.webp downloadded successfully
28.webp downloadded successfully
3.webp downloadded successfully
16.webp downloadded successfully
stream error: stream ID 41; INTERNAL_ERROR; received from peer
stream error: stream ID 33; INTERNAL_ERROR; received from peer
stream error: stream ID 49; INTERNAL_ERROR; received from peer
stream error: stream ID 37; INTERNAL_ERROR; received from peer
stream error: stream ID 31; INTERNAL_ERROR; received from peer
stream error: stream ID 43; INTERNAL_ERROR; received from peer
1.webp downloadded successfully
stream error: stream ID 51; INTERNAL_ERROR; received from peer
stream error: stream ID 39; INTERNAL_ERROR; received from peer
stream error: stream ID 11; INTERNAL_ERROR; received from peer
stream error: stream ID 35; INTERNAL_ERROR; received from peer
stream error: stream ID 47; INTERNAL_ERROR; received from peer
stream error: stream ID 53; INTERNAL_ERROR; received from peer
stream error: stream ID 45; INTERNAL_ERROR; received from peer
stream error: stream ID 29; INTERNAL_ERROR; received from peer
stream error: stream ID 55; INTERNAL_ERROR; received from peer
stream error: stream ID 57; INTERNAL_ERROR; received from peer
stream error: stream ID 27; INTERNAL_ERROR; received from peer
```

**Comment by ry023** [comment]
I have found that the problem occurs when the HTTP2 module returns NGX_AGAIN.

It looks like the problem is that NGX_ERROR is returned when NGX_AGAIN is retrieved in this part;
https://github.com/matsumotory/ngx_mruby/blob/master/src/http/ngx_http_mruby_module.c#L1781-L1783

I'll create pull request later!

**Comment by pyama86** [comment]
header_filter_handlerでagain返ってくることあるのか。。
