### ISSUE TITLE
We should implement non-blocking I/O like neverblock

### ISSUE THREAD

**Issue by matsumotory** [matsumotory/ngx_mruby#78]
We should implement non-blocking I/O like neverblock. nginx architecture has non-blocking and async I/O. So, when accessing external db like redis or mysql, this access should be non-blocking. Now, this access is blocking.

my plans are the followings:
- use mruby-fiber
- implement as mrbgem (mruby-neverblock?)
- can write code like [neverblock](http://stackoverflow.com/questions/2593538/simple-neverblock-example-doesnt-work)

I'ts NOT easy to implement.

**Comment by davydovanton** [comment]
@matsumoto-r what about status of this PR? Because non blocked IO is very needful feature for me :disappointed:

**Comment by matsumoto-r** [comment]
@davydovanton I now have an idea for this issue, but just an idea. So, I try to implement this feature next year!!

ref: https://speakerdeck.com/matsumoto_r/the-future-of-mruby-in-http-server-rubykaigi-2015?slide=56

**Comment by jpsikorra** [comment]
What's the current state? Any progress?

**Comment by matsumotory** [comment]
more information for nonblocking architecture is here: https://speakerdeck.com/matsumoto_r/design-pattern-for-embedding-mruby-into-middleware

**Comment by matsumotory** [comment]
Thanks all!
